 graph = np.stack((years, gdb), axis=1)
    interpolation_graph = np.vectorize(lambda x: lagrange_interpolation(x, years, gdb))
    plt.scatter(graph[:,0], graph[:,1], color='red', label='Data Points')
    x = np.linspace(min(years), max(years), 100)
    plt.plot(x, interpolation_graph(x), color='blue', label='Lagrange Interpolation')
    plt.xlabel('Year')
    plt.ylabel('GDP')
    plt.legend()
    return plt.show()